apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuetify-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuetify-sample
  template:
    metadata:
      labels:
        app: vuetify-sample
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        name: vuetify-sample
        image: kloudbank/vuetify-sample:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # readinessProbe:
        #     failureThreshold: 3
        #     successThreshold: 1
        #     httpGet:
        #         path: /
        #         port: 3000
        #         scheme: HTTP
        #     initialDelaySeconds: 10
        #     periodSeconds: 3
        # livenessProbe:
        #     failureThreshold: 3
        #     successThreshold: 1
        #     httpGet:
        #         path: /
        #         port: 3000
        #         scheme: HTTP
        #     initialDelaySeconds: 20
        #     periodSeconds: 3
        # resources:
        #   limits:
        #     cpu: 1000m
        #     memory: 512Mi
        #   requests:
        #     cpu: 200m
        #     memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vuetify-sample
  labels:
    app: vuetify-sample
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: vuetify-sample
  selector:
    app: vuetify-sample
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vuetify-sample
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: vuetify-sample.nogada.kubepia.net
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vuetify-sample
            port:
              number: 3000